name = "SimpleParticleInCell"
uuid = "f955a326-fb8f-4775-9897-b43373bf555f"
authors = ["Dominik Stańczak <stanczakdominik@gmail.com> and contributors"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "0.12"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
